# (probably) get resin.io rpi image
FROM resin/rpi-resin/rpi-raspbian

# apt-get update or equivalent

RUN apt-get update

ENTRYPOINT [ "bash" ]

# install python 3.x
# install packages needed for Flask/omxplayer etc

# install everything needed to set up the 'Pi as a hotspot

# install rclone

# get gdrive credentials

# run rclone
# Sample Command for rclone:
# rclone sync remote_mlp:mlp-samples-test ./mlp_files/ -v -P

# set up rclone chronjob (updated every evening?)

# copy mw_serve repo

# build angular app

# serve Flask from 5002