#!/usr/bin/expect -f
spawn rclone config
expect "e/n/d/r/c/s/q> "
send "n\r"
expect "name> "
send "arupiot-expect\r"
expect "Storage> "
send "drive\r"
expect "client_id> "
send "\r"
expect "client_secret> "
send "\r"
expect "scope> "
send "drive.readonly\r"
expect "root_folder_id> "
send "\r"
expect "service_account_file> "
send "/media/usb/rclone/media-warrior-07dec249ae7a.json\r"
expect "y/n> "
send "n\r"
expect "y/n> "
send "n\r"
expect "y/e/d> "
send "y\r"
expect "e/n/d/r/c/s/q> "
send "q\r"
